output vulnerability in github action log

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -75,19 +75,50 @@ jobs:
         scan-ref: sbom.json
         format: table
         exit-code: 0
-        # output: vuln-report.txt
+        output: vuln-report.txt
         severity: CRITICAL,HIGH
 
+    - name: Print scan report
+      run: cat vuln-report.txt
 
-    # - name: Upload vulnerability report artifact
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: vulnerability-report
-    #     path: vuln-report.txt
+
+    - name: Upload vulnerability report artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: vulnerability-report
+        path: vuln-report.txt
+
+  review:
+    runs-on: ubuntu-latest
+    needs: [run_test, pre_release]
+    name: Review test and security scan result
+    steps:
+    - name: Get Artifact ID and Print URL for review
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        REPO: ${{ github.repository }}
+        RUN_ID: ${{ github.run_id }}
+      run: |
+        ARTIFACT_NAME="vulnerability-report"
+
+        echo "Fetching artifact ID for ${ARTIFACT_NAME}..."
+        ARTIFACTS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
+          -H "Accept: application/vnd.github+json" \
+          https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts)
+
+        ARTIFACT_ID=$(echo "$ARTIFACTS" | jq -r ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")
+
+        if [ -z "$ARTIFACT_ID" ]; then
+          echo "❌ Artifact not found."
+          exit 1
+        fi
+
+        echo "✅ Artifact ID: $ARTIFACT_ID"
+        echo "🔗 Review URL: https://github.com/$REPO/suites/${{ github.run_id }}/artifacts/$ARTIFACT_ID"
 
   release:
     runs-on: ubuntu-latest
-    needs: [run_test, pre_release]
+    needs: [run_test, pre_release, review]
     name: Release Pipeline for ${{ github.event.inputs.package_version }}
     environment:
       name: manual-approval
